"Filed out from Dolphin Smalltalk 7"!

Error subclass: #AssertionFailed
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
AssertionFailed guid: (GUID fromString: '{9fe98040-b7c1-498d-b095-0c8e3c752480}')!
AssertionFailed comment: 'Object subclass: #AssertionFailurePolicy	instanceVariableNames: ''''	classVariableNames: ''''	poolDictionaries: ''''	category: ''Buoy-Assertions'''!
!AssertionFailed categoriesForClass!Buoy-Assertions! !
