"Filed out from Dolphin Smalltalk 7"!

WADeploymentAwareFileMetadataLibrary subclass: #BootstrapTypeaheadLibrary
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
BootstrapTypeaheadLibrary guid: (GUID fromString: '{46f13be3-15d3-4f52-8c7a-9d7248db5bc4}')!
BootstrapTypeaheadLibrary comment: 'BootstrapTypeaheadLibrary class	instanceVariableNames: '''''!
!BootstrapTypeaheadLibrary categoriesForClass!Willow-Bootstrap-Typeahead! !
!BootstrapTypeaheadLibrary class methodsFor!

forDeployment	^ BootstrapTypeaheadDeploymentLibrary!

forDevelopment	^ BootstrapTypeaheadDevelopmentLibrary!

libraryName	^ 'bootstrap-typeahead'!

version	^ '4.0.2'! !
!BootstrapTypeaheadLibrary class categoriesFor: #forDeployment!Accessing!public! !
!BootstrapTypeaheadLibrary class categoriesFor: #forDevelopment!Accessing!public! !
!BootstrapTypeaheadLibrary class categoriesFor: #libraryName!Accessing!public! !
!BootstrapTypeaheadLibrary class categoriesFor: #version!public!versions! !

