"Filed out from Dolphin Smalltalk 7"!

BootstrapPlugin subclass: #BootstrapDropdown
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
BootstrapDropdown guid: (GUID fromString: '{ee294ff9-b89b-49bf-92c1-bd38b6dc3797}')!
BootstrapDropdown comment: 'Add dropdown menus to nearly anything with this simple plugin, including the navbar, tabs, and pills.'!
!BootstrapDropdown categoriesForClass!Willow-Bootstrap-Plugins! !
!BootstrapDropdown methodsFor!

method	^ self lookupValue: #dropdown!

toggle	functionName := self lookupValue: #toggle! !
!BootstrapDropdown categoriesFor: #method!private! !
!BootstrapDropdown categoriesFor: #toggle!Methods!public! !

