"Filed out from Dolphin Smalltalk 7"!

CssRulePrecedencePolicy subclass: #CssNormalRulePrecedencePolicy
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
CssNormalRulePrecedencePolicy guid: (GUID fromString: '{fb8d77c2-ff48-4d8f-bb1a-dc9173a49468}')!
CssNormalRulePrecedencePolicy comment: 'A CssNormalRulePrecedencePolicy is a policy indicating an standard declaration.'!
!CssNormalRulePrecedencePolicy categoriesForClass!RenoirSt-Common! !
!CssNormalRulePrecedencePolicy methodsFor!

applyTo: aCssDeclaration 		^aCssDeclaration ! !
!CssNormalRulePrecedencePolicy categoriesFor: #applyTo:!Applying!public! !

