"Filed out from Dolphin Smalltalk 7"!

Object subclass: #Glyphicons
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Glyphicons guid: (GUID fromString: '{4a394c76-f2ba-46b3-8f13-f9a85e0e7b3f}')!
Glyphicons comment: 'glyphicon-comment'!
!Glyphicons categoriesForClass!Willow-Bootstrap-WebViews! !
!Glyphicons class methodsFor!

adjust	^'glyphicon-adjust'!

alert	^'glyphicon-alert'!

alignCenter	^'glyphicon-align-center'!

alignJustify	^'glyphicon-align-justify'!

alignLeft	^'glyphicon-align-left'!

alignRight	^'glyphicon-align-right'!

apple	^'glyphicon-apple'!

arrowDown	^'glyphicon-arrow-down'!

arrowLeft	^'glyphicon-arrow-left'!

arrowRight	^'glyphicon-arrow-right'!

arrowUp	^'glyphicon-arrow-up'!

asterisk	^'glyphicon-asterisk'!

babyFormula	^'glyphicon-baby-formula'!

backward	^'glyphicon-backward'!

banCircle	^'glyphicon-ban-circle'!

barcode	^'glyphicon-barcode'!

bed	^'glyphicon-bed'!

bell	^'glyphicon-bell'!

bishop	^'glyphicon-bishop'!

bitcoin	^'glyphicon-bitcoin'!

blackboard	^'glyphicon-blackboard'!

bold	^'glyphicon-bold'!

book	^'glyphicon-book'!

bookmark	^'glyphicon-bookmark'!

briefcase	^'glyphicon-briefcase'!

btc	^'glyphicon-btc'!

bullhorn	^'glyphicon-bullhorn'!

calendar	^'glyphicon-calendar'!

camera	^'glyphicon-camera'!

cd	^'glyphicon-cd'!

certificate	^'glyphicon-certificate'!

check	^'glyphicon-check'!

chevronDown	^'glyphicon-chevron-down'!

chevronLeft	^'glyphicon-chevron-left'!

chevronRight	^'glyphicon-chevron-right'!

chevronUp	^'glyphicon-chevron-up'!

circleArrowDown	^'glyphicon-circle-arrow-down'!

circleArrowLeft	^'glyphicon-circle-arrow-left'!

circleArrowRight	^'glyphicon-circle-arrow-right'!

circleArrowUp	^'glyphicon-circle-arrow-up'!

cloud	^'glyphicon-cloud'!

cloudDownload	^'glyphicon-cloud-download'!

cloudUpload	^'glyphicon-cloud-upload'!

cog	^'glyphicon-cog'!

collapseDown	^'glyphicon-collapse-down'!

collapseUp	^'glyphicon-collapse-up'!

comment	^'glyphicon-comment'!

compressed	^'glyphicon-compressed'!

console	^'glyphicon-console'!

copy	^'glyphicon-copy'!

copyrightMark	^'glyphicon-copyright-mark'!

creditCard	^'glyphicon-credit-card'!

cutlery	^'glyphicon-cutlery'!

dashboard	^'glyphicon-dashboard'!

download	^'glyphicon-download'!

downloadAlt	^'glyphicon-download-alt'!

duplicate	^'glyphicon-duplicate'!

earphone	^'glyphicon-earphone'!

edit	^'glyphicon-edit'!

education	^'glyphicon-education'!

eject	^'glyphicon-eject'!

envelope	^'glyphicon-envelope'!

equalizer	^'glyphicon-equalizer'!

erase	^'glyphicon-erase'!

eur	^'glyphicon-eur'!

euro	^'glyphicon-euro'!

exclamationSign	^'glyphicon-exclamation-sign'!

expand	^'glyphicon-expand'!

export	^'glyphicon-export'!

eyeClose	^'glyphicon-eye-close'!

eyeOpen	^'glyphicon-eye-open'!

facetimeVideo	^'glyphicon-facetime-video'!

fastBackward	^'glyphicon-fast-backward'!

fastForward	^'glyphicon-fast-forward'!

file	^'glyphicon-file'!

film	^'glyphicon-film'!

filter	^'glyphicon-filter'!

fire	^'glyphicon-fire'!

flag	^'glyphicon-flag'!

flash	^'glyphicon-flash'!

floppyDisk	^'glyphicon-floppy-disk'!

floppyOpen	^'glyphicon-floppy-open'!

floppyRemove	^'glyphicon-floppy-remove'!

floppySave	^'glyphicon-floppy-save'!

floppySaved	^'glyphicon-floppy-saved'!

folderClose	^'glyphicon-folder-close'!

folderOpen	^'glyphicon-folder-open'!

font	^'glyphicon-font'!

forward	^'glyphicon-forward'!

fullscreen	^'glyphicon-fullscreen'!

gbp	^'glyphicon-gbp'!

gift	^'glyphicon-gift'!

glass	^'glyphicon-glass'!

globe	^'glyphicon-globe'!

grain	^'glyphicon-grain'!

handDown	^'glyphicon-hand-down'!

handLeft	^'glyphicon-hand-left'!

handRight	^'glyphicon-hand-right'!

handUp	^'glyphicon-hand-up'!

hdd	^'glyphicon-hdd'!

hdVideo	^'glyphicon-hd-video'!

header	^'glyphicon-header'!

headphones	^'glyphicon-headphones'!

heart	^'glyphicon-heart'!

heartEmpty	^'glyphicon-heart-empty'!

home	^'glyphicon-home'!

hourglass	^'glyphicon-hourglass'!

iceLolly	^'glyphicon-ice-lolly'!

iceLollyTasted	^'glyphicon-ice-lolly-tasted'!

import	^'glyphicon-import'!

inbox	^'glyphicon-inbox'!

indentLeft	^'glyphicon-indent-left'!

indentRight	^'glyphicon-indent-right'!

infoSign	^'glyphicon-info-sign'!

italic	^'glyphicon-italic'!

jpy	^'glyphicon-jpy'!

king	^'glyphicon-king'!

knight	^'glyphicon-knight'!

lamp	^'glyphicon-lamp'!

leaf	^'glyphicon-leaf'!

levelUp	^'glyphicon-level-up'!

link	^'glyphicon-link'!

list	^'glyphicon-list'!

listAlt	^'glyphicon-list-alt'!

lock	^'glyphicon-lock'!

logIn	^'glyphicon-log-in'!

logOut	^'glyphicon-log-out'!

magnet	^'glyphicon-magnet'!

mapMarker	^'glyphicon-map-marker'!

menuDown	^'glyphicon-menu-down'!

menuHamburger	^'glyphicon-menu-hamburger'!

menuLeft	^'glyphicon-menu-left'!

menuRight	^'glyphicon-menu-right'!

menuUp	^'glyphicon-menu-up'!

minus	^'glyphicon-minus'!

minusSign	^'glyphicon-minus-sign'!

modalWindow	^'glyphicon-modal-window'!

move	^'glyphicon-move'!

music	^'glyphicon-music'!

newWindow	^'glyphicon-new-window'!

objectAlignBottom	^'glyphicon-object-align-bottom'!

objectAlignHorizontal	^'glyphicon-object-align-horizontal'!

objectAlignLeft	^'glyphicon-object-align-left'!

objectAlignRight	^'glyphicon-object-align-right'!

objectAlignTop	^'glyphicon-object-align-top'!

objectAlignVertical	^'glyphicon-object-align-vertical'!

off	^'glyphicon-off'!

oil	^'glyphicon-oil'!

ok	^'glyphicon-ok'!

okCircle	^'glyphicon-ok-circle'!

okSign	^'glyphicon-ok-sign'!

open	^'glyphicon-open'!

openFile	^'glyphicon-open-file'!

optionHorizontal	^'glyphicon-option-horizontal'!

optionVertical	^'glyphicon-option-vertical'!

paperclip	^'glyphicon-paperclip'!

paste	^'glyphicon-paste'!

pause	^'glyphicon-pause'!

pawn	^'glyphicon-pawn'!

pencil	^'glyphicon-pencil'!

phone	^'glyphicon-phone'!

phoneAlt	^'glyphicon-phone-alt'!

picture	^'glyphicon-picture'!

piggyBank	^'glyphicon-piggy-bank'!

plane	^'glyphicon-plane'!

play	^'glyphicon-play'!

playCircle	^'glyphicon-play-circle'!

plus	^'glyphicon-plus'!

plusSign	^'glyphicon-plus-sign'!

print	^'glyphicon-print'!

pushpin	^'glyphicon-pushpin'!

qrcode	^'glyphicon-qrcode'!

queen	^'glyphicon-queen'!

questionSign	^'glyphicon-question-sign'!

random	^'glyphicon-random'!

record	^'glyphicon-record'!

refresh	^'glyphicon-refresh'!

registrationMark	^'glyphicon-registration-mark'!

remove	^'glyphicon-remove'!

removeCircle	^'glyphicon-remove-circle'!

removeSign	^'glyphicon-remove-sign'!

repeat	^'glyphicon-repeat'!

resizeFull	^'glyphicon-resize-full'!

resizeHorizontal	^'glyphicon-resize-horizontal'!

resizeSmall	^'glyphicon-resize-small'!

resizeVertical	^'glyphicon-resize-vertical'!

retweet	^'glyphicon-retweet'!

road	^'glyphicon-road'!

rub	^'glyphicon-rub'!

ruble	^'glyphicon-ruble'!

save	^'glyphicon-save'!

saved	^'glyphicon-saved'!

saveFile	^'glyphicon-save-file'!

scale	^'glyphicon-scale'!

scissors	^'glyphicon-scissors'!

screenshot	^'glyphicon-screenshot'!

sdVideo	^'glyphicon-sd-video'!

search	^'glyphicon-search'!

send	^'glyphicon-send'!

share	^'glyphicon-share'!

shareAlt	^'glyphicon-share-alt'!

shoppingCart	^'glyphicon-shopping-cart'!

signal	^'glyphicon-signal'!

sort	^'glyphicon-sort'!

sortByAlphabet	^'glyphicon-sort-by-alphabet'!

sortByAlphabetAlt	^'glyphicon-sort-by-alphabet-alt'!

sortByAttributes	^'glyphicon-sort-by-attributes'!

sortByAttributesAlt	^'glyphicon-sort-by-attributes-alt'!

sortByOrder	^'glyphicon-sort-by-order'!

sortByOrderAlt	^'glyphicon-sort-by-order-alt'!

sound51	^'glyphicon-sound-5-1'!

sound61	^'glyphicon-sound-6-1'!

sound71	^'glyphicon-sound-7-1'!

soundDolby	^'glyphicon-sound-dolby'!

soundStereo	^'glyphicon-sound-stereo'!

star	^'glyphicon-star'!

starEmpty	^'glyphicon-star-empty'!

stats	^'glyphicon-stats'!

stepBackward	^'glyphicon-step-backward'!

stepForward	^'glyphicon-step-forward'!

stop	^'glyphicon-stop'!

subscript	^'glyphicon-subscript'!

subtitles	^'glyphicon-subtitles'!

sunglasses	^'glyphicon-sunglasses'!

superscript	^'glyphicon-superscript'!

tag	^'glyphicon-tag'!

tags	^'glyphicon-tags'!

tasks	^'glyphicon-tasks'!

tent	^'glyphicon-tent'!

textBackground	^'glyphicon-text-background'!

textColor	^'glyphicon-text-color'!

textHeight	^'glyphicon-text-height'!

textSize	^'glyphicon-text-size'!

textWidth	^'glyphicon-text-width'!

th	^'glyphicon-th'!

thLarge	^'glyphicon-th-large'!

thList	^'glyphicon-th-list'!

thumbsDown	^'glyphicon-thumbs-down'!

thumbsUp	^'glyphicon-thumbs-up'!

time	^'glyphicon-time'!

tint	^'glyphicon-tint'!

tower	^'glyphicon-tower'!

transfer	^'glyphicon-transfer'!

trash	^'glyphicon-trash'!

treeConifer	^'glyphicon-tree-conifer'!

treeDeciduous	^'glyphicon-tree-deciduous'!

triangleBottom	^'glyphicon-triangle-bottom'!

triangleLeft	^'glyphicon-triangle-left'!

triangleRight	^'glyphicon-triangle-right'!

triangleTop	^'glyphicon-triangle-top'!

unchecked	^'glyphicon-unchecked'!

upload	^'glyphicon-upload'!

usd	^'glyphicon-usd'!

user	^'glyphicon-user'!

volumeDown	^'glyphicon-volume-down'!

volumeOff	^'glyphicon-volume-off'!

volumeUp	^'glyphicon-volume-up'!

warningSign	^'glyphicon-warning-sign'!

wrench	^'glyphicon-wrench'!

xbt	^'glyphicon-xbt'!

yen	^'glyphicon-yen'!

zoomIn	^'glyphicon-zoom-in'!

zoomOut	^'glyphicon-zoom-out'! !
!Glyphicons class categoriesFor: #adjust!Accessing!public! !
!Glyphicons class categoriesFor: #alert!Accessing!public! !
!Glyphicons class categoriesFor: #alignCenter!Accessing!public! !
!Glyphicons class categoriesFor: #alignJustify!Accessing!public! !
!Glyphicons class categoriesFor: #alignLeft!Accessing!public! !
!Glyphicons class categoriesFor: #alignRight!Accessing!public! !
!Glyphicons class categoriesFor: #apple!Accessing!public! !
!Glyphicons class categoriesFor: #arrowDown!Accessing!public! !
!Glyphicons class categoriesFor: #arrowLeft!Accessing!public! !
!Glyphicons class categoriesFor: #arrowRight!Accessing!public! !
!Glyphicons class categoriesFor: #arrowUp!Accessing!public! !
!Glyphicons class categoriesFor: #asterisk!Accessing!public! !
!Glyphicons class categoriesFor: #babyFormula!Accessing!public! !
!Glyphicons class categoriesFor: #backward!Accessing!public! !
!Glyphicons class categoriesFor: #banCircle!Accessing!public! !
!Glyphicons class categoriesFor: #barcode!Accessing!public! !
!Glyphicons class categoriesFor: #bed!Accessing!public! !
!Glyphicons class categoriesFor: #bell!Accessing!public! !
!Glyphicons class categoriesFor: #bishop!Accessing!public! !
!Glyphicons class categoriesFor: #bitcoin!Accessing!public! !
!Glyphicons class categoriesFor: #blackboard!Accessing!public! !
!Glyphicons class categoriesFor: #bold!Accessing!public! !
!Glyphicons class categoriesFor: #book!Accessing!public! !
!Glyphicons class categoriesFor: #bookmark!Accessing!public! !
!Glyphicons class categoriesFor: #briefcase!Accessing!public! !
!Glyphicons class categoriesFor: #btc!Accessing!public! !
!Glyphicons class categoriesFor: #bullhorn!Accessing!public! !
!Glyphicons class categoriesFor: #calendar!Accessing!public! !
!Glyphicons class categoriesFor: #camera!Accessing!public! !
!Glyphicons class categoriesFor: #cd!Accessing!public! !
!Glyphicons class categoriesFor: #certificate!Accessing!public! !
!Glyphicons class categoriesFor: #check!Accessing!public! !
!Glyphicons class categoriesFor: #chevronDown!Accessing!public! !
!Glyphicons class categoriesFor: #chevronLeft!Accessing!public! !
!Glyphicons class categoriesFor: #chevronRight!Accessing!public! !
!Glyphicons class categoriesFor: #chevronUp!Accessing!public! !
!Glyphicons class categoriesFor: #circleArrowDown!Accessing!public! !
!Glyphicons class categoriesFor: #circleArrowLeft!Accessing!public! !
!Glyphicons class categoriesFor: #circleArrowRight!Accessing!public! !
!Glyphicons class categoriesFor: #circleArrowUp!Accessing!public! !
!Glyphicons class categoriesFor: #cloud!Accessing!public! !
!Glyphicons class categoriesFor: #cloudDownload!Accessing!public! !
!Glyphicons class categoriesFor: #cloudUpload!Accessing!public! !
!Glyphicons class categoriesFor: #cog!Accessing!public! !
!Glyphicons class categoriesFor: #collapseDown!Accessing!public! !
!Glyphicons class categoriesFor: #collapseUp!Accessing!public! !
!Glyphicons class categoriesFor: #comment!Accessing!public! !
!Glyphicons class categoriesFor: #compressed!Accessing!public! !
!Glyphicons class categoriesFor: #console!Accessing!public! !
!Glyphicons class categoriesFor: #copy!Accessing!public! !
!Glyphicons class categoriesFor: #copyrightMark!Accessing!public! !
!Glyphicons class categoriesFor: #creditCard!Accessing!public! !
!Glyphicons class categoriesFor: #cutlery!Accessing!public! !
!Glyphicons class categoriesFor: #dashboard!Accessing!public! !
!Glyphicons class categoriesFor: #download!Accessing!public! !
!Glyphicons class categoriesFor: #downloadAlt!Accessing!public! !
!Glyphicons class categoriesFor: #duplicate!Accessing!public! !
!Glyphicons class categoriesFor: #earphone!Accessing!public! !
!Glyphicons class categoriesFor: #edit!Accessing!public! !
!Glyphicons class categoriesFor: #education!Accessing!public! !
!Glyphicons class categoriesFor: #eject!Accessing!public! !
!Glyphicons class categoriesFor: #envelope!Accessing!public! !
!Glyphicons class categoriesFor: #equalizer!Accessing!public! !
!Glyphicons class categoriesFor: #erase!Accessing!public! !
!Glyphicons class categoriesFor: #eur!Accessing!public! !
!Glyphicons class categoriesFor: #euro!Accessing!public! !
!Glyphicons class categoriesFor: #exclamationSign!Accessing!public! !
!Glyphicons class categoriesFor: #expand!Accessing!public! !
!Glyphicons class categoriesFor: #export!Accessing!public! !
!Glyphicons class categoriesFor: #eyeClose!Accessing!public! !
!Glyphicons class categoriesFor: #eyeOpen!Accessing!public! !
!Glyphicons class categoriesFor: #facetimeVideo!Accessing!public! !
!Glyphicons class categoriesFor: #fastBackward!Accessing!public! !
!Glyphicons class categoriesFor: #fastForward!Accessing!public! !
!Glyphicons class categoriesFor: #file!Accessing!public! !
!Glyphicons class categoriesFor: #film!Accessing!public! !
!Glyphicons class categoriesFor: #filter!Accessing!public! !
!Glyphicons class categoriesFor: #fire!Accessing!public! !
!Glyphicons class categoriesFor: #flag!Accessing!public! !
!Glyphicons class categoriesFor: #flash!Accessing!public! !
!Glyphicons class categoriesFor: #floppyDisk!Accessing!public! !
!Glyphicons class categoriesFor: #floppyOpen!Accessing!public! !
!Glyphicons class categoriesFor: #floppyRemove!Accessing!public! !
!Glyphicons class categoriesFor: #floppySave!Accessing!public! !
!Glyphicons class categoriesFor: #floppySaved!Accessing!public! !
!Glyphicons class categoriesFor: #folderClose!Accessing!public! !
!Glyphicons class categoriesFor: #folderOpen!Accessing!public! !
!Glyphicons class categoriesFor: #font!Accessing!public! !
!Glyphicons class categoriesFor: #forward!Accessing!public! !
!Glyphicons class categoriesFor: #fullscreen!Accessing!public! !
!Glyphicons class categoriesFor: #gbp!Accessing!public! !
!Glyphicons class categoriesFor: #gift!Accessing!public! !
!Glyphicons class categoriesFor: #glass!Accessing!public! !
!Glyphicons class categoriesFor: #globe!Accessing!public! !
!Glyphicons class categoriesFor: #grain!Accessing!public! !
!Glyphicons class categoriesFor: #handDown!Accessing!public! !
!Glyphicons class categoriesFor: #handLeft!Accessing!public! !
!Glyphicons class categoriesFor: #handRight!Accessing!public! !
!Glyphicons class categoriesFor: #handUp!Accessing!public! !
!Glyphicons class categoriesFor: #hdd!Accessing!public! !
!Glyphicons class categoriesFor: #hdVideo!Accessing!public! !
!Glyphicons class categoriesFor: #header!Accessing!public! !
!Glyphicons class categoriesFor: #headphones!Accessing!public! !
!Glyphicons class categoriesFor: #heart!Accessing!public! !
!Glyphicons class categoriesFor: #heartEmpty!Accessing!public! !
!Glyphicons class categoriesFor: #home!Accessing!public! !
!Glyphicons class categoriesFor: #hourglass!Accessing!public! !
!Glyphicons class categoriesFor: #iceLolly!Accessing!public! !
!Glyphicons class categoriesFor: #iceLollyTasted!Accessing!public! !
!Glyphicons class categoriesFor: #import!Accessing!public! !
!Glyphicons class categoriesFor: #inbox!Accessing!public! !
!Glyphicons class categoriesFor: #indentLeft!Accessing!public! !
!Glyphicons class categoriesFor: #indentRight!Accessing!public! !
!Glyphicons class categoriesFor: #infoSign!Accessing!public! !
!Glyphicons class categoriesFor: #italic!Accessing!public! !
!Glyphicons class categoriesFor: #jpy!Accessing!public! !
!Glyphicons class categoriesFor: #king!Accessing!public! !
!Glyphicons class categoriesFor: #knight!Accessing!public! !
!Glyphicons class categoriesFor: #lamp!Accessing!public! !
!Glyphicons class categoriesFor: #leaf!Accessing!public! !
!Glyphicons class categoriesFor: #levelUp!Accessing!public! !
!Glyphicons class categoriesFor: #link!Accessing!public! !
!Glyphicons class categoriesFor: #list!Accessing!public! !
!Glyphicons class categoriesFor: #listAlt!Accessing!public! !
!Glyphicons class categoriesFor: #lock!Accessing!public! !
!Glyphicons class categoriesFor: #logIn!Accessing!public! !
!Glyphicons class categoriesFor: #logOut!Accessing!public! !
!Glyphicons class categoriesFor: #magnet!Accessing!public! !
!Glyphicons class categoriesFor: #mapMarker!Accessing!public! !
!Glyphicons class categoriesFor: #menuDown!Accessing!public! !
!Glyphicons class categoriesFor: #menuHamburger!Accessing!public! !
!Glyphicons class categoriesFor: #menuLeft!Accessing!public! !
!Glyphicons class categoriesFor: #menuRight!Accessing!public! !
!Glyphicons class categoriesFor: #menuUp!Accessing!public! !
!Glyphicons class categoriesFor: #minus!Accessing!public! !
!Glyphicons class categoriesFor: #minusSign!Accessing!public! !
!Glyphicons class categoriesFor: #modalWindow!Accessing!public! !
!Glyphicons class categoriesFor: #move!Accessing!public! !
!Glyphicons class categoriesFor: #music!Accessing!public! !
!Glyphicons class categoriesFor: #newWindow!Accessing!public! !
!Glyphicons class categoriesFor: #objectAlignBottom!Accessing!public! !
!Glyphicons class categoriesFor: #objectAlignHorizontal!Accessing!public! !
!Glyphicons class categoriesFor: #objectAlignLeft!Accessing!public! !
!Glyphicons class categoriesFor: #objectAlignRight!Accessing!public! !
!Glyphicons class categoriesFor: #objectAlignTop!Accessing!public! !
!Glyphicons class categoriesFor: #objectAlignVertical!Accessing!public! !
!Glyphicons class categoriesFor: #off!Accessing!public! !
!Glyphicons class categoriesFor: #oil!Accessing!public! !
!Glyphicons class categoriesFor: #ok!Accessing!public! !
!Glyphicons class categoriesFor: #okCircle!Accessing!public! !
!Glyphicons class categoriesFor: #okSign!Accessing!public! !
!Glyphicons class categoriesFor: #open!Accessing!public! !
!Glyphicons class categoriesFor: #openFile!Accessing!public! !
!Glyphicons class categoriesFor: #optionHorizontal!Accessing!public! !
!Glyphicons class categoriesFor: #optionVertical!Accessing!public! !
!Glyphicons class categoriesFor: #paperclip!Accessing!public! !
!Glyphicons class categoriesFor: #paste!Accessing!public! !
!Glyphicons class categoriesFor: #pause!Accessing!public! !
!Glyphicons class categoriesFor: #pawn!Accessing!public! !
!Glyphicons class categoriesFor: #pencil!Accessing!public! !
!Glyphicons class categoriesFor: #phone!Accessing!public! !
!Glyphicons class categoriesFor: #phoneAlt!Accessing!public! !
!Glyphicons class categoriesFor: #picture!Accessing!public! !
!Glyphicons class categoriesFor: #piggyBank!Accessing!public! !
!Glyphicons class categoriesFor: #plane!Accessing!public! !
!Glyphicons class categoriesFor: #play!Accessing!public! !
!Glyphicons class categoriesFor: #playCircle!Accessing!public! !
!Glyphicons class categoriesFor: #plus!Accessing!public! !
!Glyphicons class categoriesFor: #plusSign!Accessing!public! !
!Glyphicons class categoriesFor: #print!Accessing!public! !
!Glyphicons class categoriesFor: #pushpin!Accessing!public! !
!Glyphicons class categoriesFor: #qrcode!Accessing!public! !
!Glyphicons class categoriesFor: #queen!Accessing!public! !
!Glyphicons class categoriesFor: #questionSign!Accessing!public! !
!Glyphicons class categoriesFor: #random!Accessing!public! !
!Glyphicons class categoriesFor: #record!Accessing!public! !
!Glyphicons class categoriesFor: #refresh!Accessing!public! !
!Glyphicons class categoriesFor: #registrationMark!Accessing!public! !
!Glyphicons class categoriesFor: #remove!Accessing!public! !
!Glyphicons class categoriesFor: #removeCircle!Accessing!public! !
!Glyphicons class categoriesFor: #removeSign!Accessing!public! !
!Glyphicons class categoriesFor: #repeat!Accessing!public! !
!Glyphicons class categoriesFor: #resizeFull!Accessing!public! !
!Glyphicons class categoriesFor: #resizeHorizontal!Accessing!public! !
!Glyphicons class categoriesFor: #resizeSmall!Accessing!public! !
!Glyphicons class categoriesFor: #resizeVertical!Accessing!public! !
!Glyphicons class categoriesFor: #retweet!Accessing!public! !
!Glyphicons class categoriesFor: #road!Accessing!public! !
!Glyphicons class categoriesFor: #rub!Accessing!public! !
!Glyphicons class categoriesFor: #ruble!Accessing!public! !
!Glyphicons class categoriesFor: #save!Accessing!public! !
!Glyphicons class categoriesFor: #saved!Accessing!public! !
!Glyphicons class categoriesFor: #saveFile!Accessing!public! !
!Glyphicons class categoriesFor: #scale!Accessing!public! !
!Glyphicons class categoriesFor: #scissors!Accessing!public! !
!Glyphicons class categoriesFor: #screenshot!Accessing!public! !
!Glyphicons class categoriesFor: #sdVideo!Accessing!public! !
!Glyphicons class categoriesFor: #search!Accessing!public! !
!Glyphicons class categoriesFor: #send!Accessing!public! !
!Glyphicons class categoriesFor: #share!Accessing!public! !
!Glyphicons class categoriesFor: #shareAlt!Accessing!public! !
!Glyphicons class categoriesFor: #shoppingCart!Accessing!public! !
!Glyphicons class categoriesFor: #signal!Accessing!public! !
!Glyphicons class categoriesFor: #sort!Accessing!public! !
!Glyphicons class categoriesFor: #sortByAlphabet!Accessing!public! !
!Glyphicons class categoriesFor: #sortByAlphabetAlt!Accessing!public! !
!Glyphicons class categoriesFor: #sortByAttributes!Accessing!public! !
!Glyphicons class categoriesFor: #sortByAttributesAlt!Accessing!public! !
!Glyphicons class categoriesFor: #sortByOrder!Accessing!public! !
!Glyphicons class categoriesFor: #sortByOrderAlt!Accessing!public! !
!Glyphicons class categoriesFor: #sound51!Accessing!public! !
!Glyphicons class categoriesFor: #sound61!Accessing!public! !
!Glyphicons class categoriesFor: #sound71!Accessing!public! !
!Glyphicons class categoriesFor: #soundDolby!Accessing!public! !
!Glyphicons class categoriesFor: #soundStereo!Accessing!public! !
!Glyphicons class categoriesFor: #star!Accessing!public! !
!Glyphicons class categoriesFor: #starEmpty!Accessing!public! !
!Glyphicons class categoriesFor: #stats!Accessing!public! !
!Glyphicons class categoriesFor: #stepBackward!Accessing!public! !
!Glyphicons class categoriesFor: #stepForward!Accessing!public! !
!Glyphicons class categoriesFor: #stop!Accessing!public! !
!Glyphicons class categoriesFor: #subscript!Accessing!public! !
!Glyphicons class categoriesFor: #subtitles!Accessing!public! !
!Glyphicons class categoriesFor: #sunglasses!Accessing!public! !
!Glyphicons class categoriesFor: #superscript!Accessing!public! !
!Glyphicons class categoriesFor: #tag!Accessing!public! !
!Glyphicons class categoriesFor: #tags!Accessing!public! !
!Glyphicons class categoriesFor: #tasks!Accessing!public! !
!Glyphicons class categoriesFor: #tent!Accessing!public! !
!Glyphicons class categoriesFor: #textBackground!Accessing!public! !
!Glyphicons class categoriesFor: #textColor!Accessing!public! !
!Glyphicons class categoriesFor: #textHeight!Accessing!public! !
!Glyphicons class categoriesFor: #textSize!Accessing!public! !
!Glyphicons class categoriesFor: #textWidth!Accessing!public! !
!Glyphicons class categoriesFor: #th!Accessing!public! !
!Glyphicons class categoriesFor: #thLarge!Accessing!public! !
!Glyphicons class categoriesFor: #thList!Accessing!public! !
!Glyphicons class categoriesFor: #thumbsDown!Accessing!public! !
!Glyphicons class categoriesFor: #thumbsUp!Accessing!public! !
!Glyphicons class categoriesFor: #time!Accessing!public! !
!Glyphicons class categoriesFor: #tint!Accessing!public! !
!Glyphicons class categoriesFor: #tower!Accessing!public! !
!Glyphicons class categoriesFor: #transfer!Accessing!public! !
!Glyphicons class categoriesFor: #trash!Accessing!public! !
!Glyphicons class categoriesFor: #treeConifer!Accessing!public! !
!Glyphicons class categoriesFor: #treeDeciduous!Accessing!public! !
!Glyphicons class categoriesFor: #triangleBottom!Accessing!public! !
!Glyphicons class categoriesFor: #triangleLeft!Accessing!public! !
!Glyphicons class categoriesFor: #triangleRight!Accessing!public! !
!Glyphicons class categoriesFor: #triangleTop!Accessing!public! !
!Glyphicons class categoriesFor: #unchecked!Accessing!public! !
!Glyphicons class categoriesFor: #upload!Accessing!public! !
!Glyphicons class categoriesFor: #usd!Accessing!public! !
!Glyphicons class categoriesFor: #user!Accessing!public! !
!Glyphicons class categoriesFor: #volumeDown!Accessing!public! !
!Glyphicons class categoriesFor: #volumeOff!Accessing!public! !
!Glyphicons class categoriesFor: #volumeUp!Accessing!public! !
!Glyphicons class categoriesFor: #warningSign!Accessing!public! !
!Glyphicons class categoriesFor: #wrench!Accessing!public! !
!Glyphicons class categoriesFor: #xbt!Accessing!public! !
!Glyphicons class categoriesFor: #yen!Accessing!public! !
!Glyphicons class categoriesFor: #zoomIn!Accessing!public! !
!Glyphicons class categoriesFor: #zoomOut!Accessing!public! !

