"Filed out from Dolphin Smalltalk 7"!

Error subclass: #InstanceCreationFailed
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
InstanceCreationFailed guid: (GUID fromString: '{2c18f9e3-b9dc-40fe-a2c8-2dd7ab3b4d27}')!
InstanceCreationFailed comment: 'Error subclass: #ObjectNotFound	instanceVariableNames: ''''	classVariableNames: ''''	poolDictionaries: ''''	category: ''Buoy-Assertions'''!
!InstanceCreationFailed categoriesForClass!Buoy-Assertions! !
