"Filed out from Dolphin Smalltalk 7"!

WAPainter subclass: #SpinKitRotatingPlane
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SpinKitRotatingPlane guid: (GUID fromString: '{c80fa1d6-62a4-40de-a194-6969d46a2dc8}')!
SpinKitRotatingPlane comment: 'I''m an SpinKit animation'!
!SpinKitRotatingPlane categoriesForClass!Willow-SpinKit! !
!SpinKitRotatingPlane methodsFor!

renderContentOn: aCanvas	aCanvas div class: SpinKitCssStyles rotatingPlane! !
!SpinKitRotatingPlane categoriesFor: #renderContentOn:!public!rendering! !

