"Filed out from Dolphin Smalltalk 7"!

Object subclass: #SpinKitCssStyles
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SpinKitCssStyles guid: (GUID fromString: '{6bcdf3d8-34c8-4fb6-8bd3-b2a7a5b7730e}')!
SpinKitCssStyles comment: 'SpinKitCssStyles class	instanceVariableNames: '''''!
!SpinKitCssStyles categoriesForClass!Willow-SpinKit! !
!SpinKitCssStyles class methodsFor!

bounce: index	^ 'sk-bounce<1p>' expandMacrosWith: index!

chasingDots	^ 'sk-chasing-dots'!

child	^ 'sk-child'!

circle	^ 'sk-circle'!

circle: index	^ '<1s><2p>' expandMacrosWith: self circle with: index!

cube	^ 'sk-cube'!

cube: index	^ '<1s><2p>' expandMacrosWith: self cube with: index!

cubeGrid	^ 'sk-cube-grid'!

dot: index	^ 'sk-dot<1p>' expandMacrosWith: index!

doubleBounce	^ 'sk-double-bounce'!

doubleBounce: index	^ '<1s><2p>' expandMacrosWith: self doubleBounce with: index!

fadingCircle	^ 'sk-fading-circle'!

foldingCube	^ 'sk-folding-cube'!

rect	^ 'sk-rect'!

rect: index	^ '<1s><2p>' expandMacrosWith: self rect with: index!

rotatingPlane	^ 'sk-rotating-plane'!

spinner	^ 'sk-spinner'!

spinnerPulse	^ 'sk-spinner-pulse'!

threeBounce	^ 'sk-three-bounce'!

wanderingCubes	^ 'sk-wandering-cubes'!

wave	^ 'sk-wave'! !
!SpinKitCssStyles class categoriesFor: #bounce:!Accessing!public! !
!SpinKitCssStyles class categoriesFor: #chasingDots!Accessing!public! !
!SpinKitCssStyles class categoriesFor: #child!Accessing!public! !
!SpinKitCssStyles class categoriesFor: #circle!Accessing!public! !
!SpinKitCssStyles class categoriesFor: #circle:!Accessing!public! !
!SpinKitCssStyles class categoriesFor: #cube!Accessing!public! !
!SpinKitCssStyles class categoriesFor: #cube:!Accessing!public! !
!SpinKitCssStyles class categoriesFor: #cubeGrid!Accessing!public! !
!SpinKitCssStyles class categoriesFor: #dot:!Accessing!public! !
!SpinKitCssStyles class categoriesFor: #doubleBounce!Accessing!public! !
!SpinKitCssStyles class categoriesFor: #doubleBounce:!Accessing!public! !
!SpinKitCssStyles class categoriesFor: #fadingCircle!Accessing!public! !
!SpinKitCssStyles class categoriesFor: #foldingCube!Accessing!public! !
!SpinKitCssStyles class categoriesFor: #rect!Accessing!public! !
!SpinKitCssStyles class categoriesFor: #rect:!Accessing!public! !
!SpinKitCssStyles class categoriesFor: #rotatingPlane!Accessing!public! !
!SpinKitCssStyles class categoriesFor: #spinner!Accessing!public! !
!SpinKitCssStyles class categoriesFor: #spinnerPulse!Accessing!public! !
!SpinKitCssStyles class categoriesFor: #threeBounce!Accessing!public! !
!SpinKitCssStyles class categoriesFor: #wanderingCubes!Accessing!public! !
!SpinKitCssStyles class categoriesFor: #wave!Accessing!public! !

