"Filed out from Dolphin Smalltalk 7"!

WATestingFileMetadataLibrary subclass: #WATestingFileMetadataDevelopmentLibrary
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WATestingFileMetadataDevelopmentLibrary guid: (GUID fromString: '{4062c784-acd7-4b43-9107-fcacea6390b0}')!
WATestingFileMetadataDevelopmentLibrary comment: 'WAOnlineLibrary subclass: #WATestingOnlineLibrary	instanceVariableNames: ''''	classVariableNames: ''''	poolDictionaries: ''''	category: ''Boardwalk-Tests-WebApplication'''!
!WATestingFileMetadataDevelopmentLibrary categoriesForClass!Boardwalk-Tests-WebApplication! !
