"Filed out from Dolphin Smalltalk 7"!

WebComponentCommand subclass: #AutoFocusComponentCommand
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
AutoFocusComponentCommand guid: (GUID fromString: '{c1f0f92b-4b34-4241-b767-958adfd78214}')!
AutoFocusComponentCommand comment: 'Command to force autofocus on rendering of a component.'!
!AutoFocusComponentCommand categoriesForClass!Willow-Core-Frontend! !
!AutoFocusComponentCommand methodsFor!

applyTo: aComponent on: aCanvas	aComponent autofocus! !
!AutoFocusComponentCommand categoriesFor: #applyTo:on:!processing!public! !

