"Filed out from Dolphin Smalltalk 7"!

BootstrapDialogClosingCommandTest subclass: #Bootstrap3DialogClosingCommandTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Bootstrap3DialogClosingCommandTest guid: (GUID fromString: '{18852875-2d1f-45c3-a26e-308c984cccd6}')!
Bootstrap3DialogClosingCommandTest comment: ''!
!Bootstrap3DialogClosingCommandTest categoriesForClass!Willow-Bootstrap-3-Tests-WebInteraction! !
!Bootstrap3DialogClosingCommandTest methodsFor!

componentSupplier	^ Bootstrap3ComponentSupplier online! !
!Bootstrap3DialogClosingCommandTest categoriesFor: #componentSupplier!accessing!public! !

