"Filed out from Dolphin Smalltalk 7"!

BootstrapModalBuilderTest subclass: #Bootstrap4ModalBuilderTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Bootstrap4ModalBuilderTest guid: (GUID fromString: '{7a310d5d-e902-4b33-9691-6a89ce0c7fa7}')!
Bootstrap4ModalBuilderTest comment: ''!
!Bootstrap4ModalBuilderTest categoriesForClass!Willow-Bootstrap-4-Tests-WebViews! !
!Bootstrap4ModalBuilderTest methodsFor!

supplier	^ Bootstrap4ComponentSupplier online! !
!Bootstrap4ModalBuilderTest categoriesFor: #supplier!private! !

