"Filed out from Dolphin Smalltalk 7"!

BootstrapDialogClosingCommandTest subclass: #Bootstrap4DialogClosingCommandTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Bootstrap4DialogClosingCommandTest guid: (GUID fromString: '{a44c7ff4-22b7-4df4-9cc6-19ddefe518d4}')!
Bootstrap4DialogClosingCommandTest comment: ''!
!Bootstrap4DialogClosingCommandTest categoriesForClass!Willow-Bootstrap-4-Tests-WebInteraction! !
!Bootstrap4DialogClosingCommandTest methodsFor!

componentSupplier	^ Bootstrap4ComponentSupplier online! !
!Bootstrap4DialogClosingCommandTest categoriesFor: #componentSupplier!accessing!public! !

