"Filed out from Dolphin Smalltalk 7"!

BootstrapModalBuilderTest subclass: #Bootstrap3ModalBuilderTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Bootstrap3ModalBuilderTest guid: (GUID fromString: '{45b86965-3afb-4720-87e1-df9c3dc72719}')!
Bootstrap3ModalBuilderTest comment: ''!
!Bootstrap3ModalBuilderTest categoriesForClass!Willow-Bootstrap-3-Tests-WebViews! !
!Bootstrap3ModalBuilderTest methodsFor!

supplier	^ Bootstrap3ComponentSupplier online! !
!Bootstrap3ModalBuilderTest categoriesFor: #supplier!private! !

