"Filed out from Dolphin Smalltalk 7"!

WebComponentCommand subclass: #ComponentRequiredCommand
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ComponentRequiredCommand guid: (GUID fromString: '{c597b865-c560-4160-b8a7-2ffd4946652f}')!
ComponentRequiredCommand comment: 'A command to set a component as required, using the HTML5 attribute.'!
!ComponentRequiredCommand categoriesForClass!Willow-Core-Frontend! !
!ComponentRequiredCommand methodsFor!

applyTo: aComponent on: aCanvas	aComponent required! !
!ComponentRequiredCommand categoriesFor: #applyTo:on:!processing!public! !

