"Filed out from Dolphin Smalltalk 7"!

Error subclass: #ConflictingObjectFound
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ConflictingObjectFound guid: (GUID fromString: '{ed4d4fcf-8d6a-4a23-9767-b956ecf427f8}')!
ConflictingObjectFound comment: 'Error subclass: #InstanceCreationFailed	instanceVariableNames: ''''	classVariableNames: ''''	package: ''Buoy-Assertions'''!
!ConflictingObjectFound categoriesForClass!Buoy-Assertions! !
