"Filed out from Dolphin Smalltalk 7"!

CssObject subclass: #CssColorUnit
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
CssColorUnit guid: (GUID fromString: '{16f7b4c3-9cc0-424e-a83d-d40c9f8768ab}')!
CssColorUnit comment: 'A CssColorUnit is an abstract color unit for CSS'!
!CssColorUnit categoriesForClass!RenoirSt-Colors! !
!CssColorUnit methodsFor!

identifiedBy: aString	self subclassResponsibility !

newWithAlpha: alphaValue 	self subclassResponsibility ! !
!CssColorUnit categoriesFor: #identifiedBy:!Converting!public! !
!CssColorUnit categoriesFor: #newWithAlpha:!Converting!public! !

