"Filed out from Dolphin Smalltalk 7"!

CssObject subclass: #CssFontReference
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
CssFontReference guid: (GUID fromString: '{21285478-c6a5-4500-b1eb-ca53aa7538d5}')!
CssFontReference comment: 'I represent a font reference'!
!CssFontReference categoriesForClass!RenoirSt-Fonts! !
!CssFontReference methodsFor!

, aCssFontReference	^CssObjectList with: self with: aCssFontReference ! !
!CssFontReference categoriesFor: #,!Concatenating!public! !

