"Filed out from Dolphin Smalltalk 7"!

CssObject subclass: #CssNoFallbackSpecified
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
CssNoFallbackSpecified guid: (GUID fromString: '{e04a8dbc-bc38-46d0-880d-c36c40bb6530}')!
CssNoFallbackSpecified comment: 'A CssNoFallbackSpecified represents tha absence of a fallback for a CSS function'!
!CssNoFallbackSpecified categoriesForClass!RenoirSt-Core-Units! !
!CssNoFallbackSpecified methodsFor!

cssContentOn: aWriteStream 	! !
!CssNoFallbackSpecified categoriesFor: #cssContentOn:!Printing!public! !

