"Filed out from Dolphin Smalltalk 7"!

CssAlphaChannel subclass: #CssNoAlphaChannelProvided
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
CssNoAlphaChannelProvided guid: (GUID fromString: '{98598096-afb4-4c53-93f3-8b544d8657eb}')!
CssNoAlphaChannelProvided comment: 'A CssNoAlphaChannelProvided represents the absence of an alpha channel. So this color is considered opaque.'!
!CssNoAlphaChannelProvided categoriesForClass!RenoirSt-Colors! !
!CssNoAlphaChannelProvided methodsFor!

componentsDo: aBlockClosure separatedBy: aSeparationBlock 	!

functionNameFor: aString 		^aString ! !
!CssNoAlphaChannelProvided categoriesFor: #componentsDo:separatedBy:!Enumerating!public! !
!CssNoAlphaChannelProvided categoriesFor: #functionNameFor:!Accessing!public! !

