"Filed out from Dolphin Smalltalk 7"!

Object subclass: #CssRulePrecedencePolicy
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
CssRulePrecedencePolicy guid: (GUID fromString: '{a5585e67-144f-45f6-aa12-01cf1f9a3f49}')!
CssRulePrecedencePolicy comment: 'A CssRulePrecedencePolicy determines the precedence policy of css declarations.'!
!CssRulePrecedencePolicy categoriesForClass!RenoirSt-Common! !
!CssRulePrecedencePolicy methodsFor!

applyTo: aCssDeclaration	self subclassResponsibility ! !
!CssRulePrecedencePolicy categoriesFor: #applyTo:!Applying!public! !

