"Filed out from Dolphin Smalltalk 7"!

WebComponentCommand subclass: #DisableComponentCommand
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
DisableComponentCommand guid: (GUID fromString: '{252ce5bd-968d-43aa-b6d2-e5c0517effef}')!
DisableComponentCommand comment: 'Command to disable a component'!
!DisableComponentCommand categoriesForClass!Willow-Core-Frontend! !
!DisableComponentCommand methodsFor!

applyTo: aComponent on: aCanvas	aComponent disabled! !
!DisableComponentCommand categoriesFor: #applyTo:on:!processing!public! !

