"Filed out from Dolphin Smalltalk 7"!

WADeploymentAwareFileMetadataLibrary subclass: #JQuery3MetadataLibrary
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQuery3MetadataLibrary guid: (GUID fromString: '{879b9f8f-6fe1-4d26-9a68-f6b946ff73a6}')!
JQuery3MetadataLibrary comment: 'JQuery3MetadataLibrary class	instanceVariableNames: '''''!
!JQuery3MetadataLibrary categoriesForClass!Willow-Libraries! !
!JQuery3MetadataLibrary class methodsFor!

forDeployment	^ JQuery3DeploymentMetadataLibrary!

forDevelopment	^ JQuery3DevelopmentMetadataLibrary!

libraryName	^ 'jQuery'!

version	^ '3.4.1'! !
!JQuery3MetadataLibrary class categoriesFor: #forDeployment!Accessing!public! !
!JQuery3MetadataLibrary class categoriesFor: #forDevelopment!Accessing!public! !
!JQuery3MetadataLibrary class categoriesFor: #libraryName!Accessing!public! !
!JQuery3MetadataLibrary class categoriesFor: #version!public!versions! !

