"Filed out from Dolphin Smalltalk 7"!

WADeploymentAwareFileMetadataLibrary subclass: #JQuery3MetadataLibrary
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQuery3MetadataLibrary guid: (GUID fromString: '{2615d8b0-620e-4680-98f6-708032cf7860}')!
JQuery3MetadataLibrary comment: 'JQuery3MetadataLibrary class	instanceVariableNames: '''''!
!JQuery3MetadataLibrary categoriesForClass!Willow-Libraries! !
!JQuery3MetadataLibrary class methodsFor!

forDeployment	^ JQuery3DeploymentMetadataLibrary!

forDevelopment	^ JQuery3DevelopmentMetadataLibrary!

libraryName	^ 'jQuery'!

version	^ '3.3.1'! !
!JQuery3MetadataLibrary class categoriesFor: #forDeployment!Accessing!public! !
!JQuery3MetadataLibrary class categoriesFor: #forDevelopment!Accessing!public! !
!JQuery3MetadataLibrary class categoriesFor: #libraryName!Accessing!public! !
!JQuery3MetadataLibrary class categoriesFor: #version!public!versions! !

