"Filed out from Dolphin Smalltalk 7"!

TableFooterWebViewBehavior subclass: #NullTableFooterWebView
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
NullTableFooterWebView guid: (GUID fromString: '{50882ebc-5e2d-46e3-991d-68517287b1e9}')!
NullTableFooterWebView comment: 'I represent the absence of a table footer'!
!NullTableFooterWebView categoriesForClass!Willow-WebViews! !
!NullTableFooterWebView methodsFor!

changeNotifiedBy: aTableWebView!

renderContentOn: canvas! !
!NullTableFooterWebView categoriesFor: #changeNotifiedBy:!public!support! !
!NullTableFooterWebView categoriesFor: #renderContentOn:!public!support! !

