"Filed out from Dolphin Smalltalk 7"!

Error subclass: #ObjectNotFound
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ObjectNotFound guid: (GUID fromString: '{51a7a281-d84a-47dd-a778-a591fc078e37}')!
ObjectNotFound comment: 'AssertionFailurePolicy subclass: #RaiseOnFirstAssertionFailurePolicy	instanceVariableNames: ''errorClass''	classVariableNames: ''''	package: ''Buoy-Assertions'''!
!ObjectNotFound categoriesForClass!Buoy-Assertions! !
