"Filed out from Dolphin Smalltalk 7"!

TestCase subclass: #ReflectiveCascadingStyleSheetBuilderExtensionTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ReflectiveCascadingStyleSheetBuilderExtensionTest guid: (GUID fromString: '{f5257773-b5be-463f-b1a5-1db08c2f8087}')!
ReflectiveCascadingStyleSheetBuilderExtensionTest comment: 'I''m a test case for Willow extensions to the CSS builder'!
!ReflectiveCascadingStyleSheetBuilderExtensionTest categoriesForClass!Willow-Tests-Frontend! !
!ReflectiveCascadingStyleSheetBuilderExtensionTest methodsFor!

testClassification	self assert: ReflectiveCascadingStyleSheetBuilder new classification equals: Willow classification! !
!ReflectiveCascadingStyleSheetBuilderExtensionTest categoriesFor: #testClassification!public!tests! !

