"Filed out from Dolphin Smalltalk 7"!

WAPainter subclass: #SpinKitPlane
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SpinKitPlane guid: (GUID fromString: '{34171a46-ba7f-4890-98a8-3d92fcc2f6f2}')!
SpinKitPlane comment: 'I''m an SpinKit animation'!
!SpinKitPlane categoriesForClass!Willow-SpinKit! !
!SpinKitPlane methodsFor!

renderContentOn: aCanvas	aCanvas div apply: [ :div | div addClass spinKit plane ]! !
!SpinKitPlane categoriesFor: #renderContentOn:!public!rendering! !

