"Filed out from Dolphin Smalltalk 7"!

WADeploymentAwareFileMetadataLibrary subclass: #SpinKitMetadataLibrary
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SpinKitMetadataLibrary guid: (GUID fromString: '{9cb66f70-7ebf-4c46-b4a5-057f909a5922}')!
SpinKitMetadataLibrary comment: 'SpinKitMetadataLibrary class	instanceVariableNames: '''''!
!SpinKitMetadataLibrary categoriesForClass!Willow-SpinKit! !
!SpinKitMetadataLibrary class methodsFor!

forDeployment	^ SpinKitDeploymentMetadataLibrary!

forDevelopment	^ SpinKitDevelopmentMetadataLibrary!

libraryName	^ 'spinkit'!

version	^'2.0.1'! !
!SpinKitMetadataLibrary class categoriesFor: #forDeployment!Accessing!public! !
!SpinKitMetadataLibrary class categoriesFor: #forDevelopment!Accessing!public! !
!SpinKitMetadataLibrary class categoriesFor: #libraryName!Accessing!public! !
!SpinKitMetadataLibrary class categoriesFor: #version!Accessing!public! !

