"Filed out from Dolphin Smalltalk 7"!

WAPainter subclass: #SpinKitPulse
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SpinKitPulse guid: (GUID fromString: '{a01dd286-1a19-4d64-8146-0e9c3df5a0ba}')!
SpinKitPulse comment: 'SpinKit animation'!
!SpinKitPulse categoriesForClass!Willow-SpinKit! !
!SpinKitPulse methodsFor!

renderContentOn: aCanvas	aCanvas div class: SpinKitCssStyles spinnerPulse! !
!SpinKitPulse categoriesFor: #renderContentOn:!public!rendering! !

