"Filed out from Dolphin Smalltalk 7"!

WAPainter subclass: #TableFooterWebViewBehavior
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
TableFooterWebViewBehavior guid: (GUID fromString: '{c9deb393-5fbb-4f32-9087-326a0d08d52d}')!
TableFooterWebViewBehavior comment: 'I''m an abstract class representing table footers'!
!TableFooterWebViewBehavior categoriesForClass!Willow-WebViews! !
!TableFooterWebViewBehavior methodsFor!

changeNotifiedBy: aTableWebView	^ self subclassResponsibility! !
!TableFooterWebViewBehavior categoriesFor: #changeNotifiedBy:!public!support! !

