"Filed out from Dolphin Smalltalk 7"!

Object subclass: #TriggeringPolicy
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
TriggeringPolicy guid: (GUID fromString: '{be846577-07f1-4729-aec1-a0688c2de15b}')!
TriggeringPolicy comment: ''!
!TriggeringPolicy categoriesForClass!Willow-Core-WebInteraction! !
!TriggeringPolicy methodsFor!

apply: anAsynchronousCall to: aComponent on: aCanvas	self subclassResponsibility! !
!TriggeringPolicy categoriesFor: #apply:to:on:!evaluating!public! !

