"Filed out from Dolphin Smalltalk 7"!

WATestingFileMetadataLibrary subclass: #WATestingFileMetadataDeploymentLibrary
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WATestingFileMetadataDeploymentLibrary guid: (GUID fromString: '{220773bd-012c-4038-9330-74d0df95c15c}')!
WATestingFileMetadataDeploymentLibrary comment: 'WATestingFileMetadataLibrary subclass: #WATestingFileMetadataDevelopmentLibrary	instanceVariableNames: ''''	classVariableNames: ''''	package: ''Boardwalk-Tests-WebApplication'''!
!WATestingFileMetadataDeploymentLibrary categoriesForClass!Boardwalk-Tests-WebApplication! !
