"Filed out from Dolphin Smalltalk 7"!

WATestingFileMetadataLibrary subclass: #WATestingFileMetadataDevelopmentLibrary
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WATestingFileMetadataDevelopmentLibrary guid: (GUID fromString: '{2c8b4240-5af5-4842-b99f-f3074d48c7a7}')!
WATestingFileMetadataDevelopmentLibrary comment: 'WAOnlineLibrary subclass: #WATestingOnlineLibrary	instanceVariableNames: ''''	classVariableNames: ''''	package: ''Boardwalk-Tests-WebApplication'''!
!WATestingFileMetadataDevelopmentLibrary categoriesForClass!Boardwalk-Tests-WebApplication! !
