"Filed out from Dolphin Smalltalk 7"!

Object subclass: #WillowSpinKit
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: 'Willow'
	classInstanceVariableNames: ''!
WillowSpinKit guid: (GUID fromString: '{de097488-52ba-4558-b85a-67038c60ca6c}')!
WillowSpinKit comment: 'WillowSpinKit class	instanceVariableNames: '''''!
!WillowSpinKit categoriesForClass!Willow-SpinKit! !
!WillowSpinKit class methodsFor!

initialize	##(Pragma ignoreForCoverage).	Classification bind: #spinKit to: Namespace new.	( Classification >> #spinKit )		bind: #plane to: 'sk-plane';		bind: #chase to: 'sk-chase';		bind: #chaseDot to: 'sk-chase-dot';		bind: #bounce to: 'sk-bounce';		bind: #bounceDot to: 'sk-bounce-dot';		bind: #wave to: 'sk-wave';		bind: #waveRectangle to: 'sk-wave-rect';		bind: #pulse to: 'sk-pulse';		bind: #flow to: 'sk-flow';		bind: #flowDot to: 'sk-flow-dot';		bind: #swing to: 'sk-swing';		bind: #swingDot to: 'sk-swing-dot';		bind: #circle to: 'sk-circle';		bind: #circleDot to: 'sk-circle-dot';		bind: #circleFade to: 'sk-circle-fade';		bind: #circleFadeDot to: 'sk-circle-fade-dot';		bind: #grid to: 'sk-grid';		bind: #gridCube to: 'sk-grid-cube';		bind: #fold to: 'sk-fold';		bind: #foldCube to: 'sk-fold-cube';		bind: #wander to: 'sk-wander';		bind: #wanderCube to: 'sk-wander-cube'! !
!WillowSpinKit class categoriesFor: #initialize!class initialization!public! !

